version: "3.7"
services:
  bootnode:
    depends_on:
         - tcpdump
    container_name: bootnode
    image: dadepo/ipfs-private:latest
    volumes:
         - /tmp/ipfs/nexus:/usr/local/nexus
    environment:
          - IS_BOOTNODE=true
    expose:
         - 8080
         - 5001
    ports:
         - 8080:8080
         - 5000:5001      
    networks:
         private_net:
            ipv4_address: "192.168.1.100"
  node1:
    depends_on: 
        - bootnode    
    container_name: node1
    image: dadepo/ipfs-private:latest
    volumes:
        - /tmp/ipfs/nexus:/usr/local/nexus/
    expose:
       - 8080
       - 5001
    ports:
         - 8081:8080
         - 5001:5001
    networks:
       private_net:
           ipv4_address: "192.168.1.101"

  node2:
    depends_on:
        - bootnode
    container_name: node2
    image: dadepo/ipfs-private:latest
    volumes:
        - /tmp/ipfs/nexus:/usr/local/nexus/
    expose:
        - 8080
        - 5001
    ports:
        - 8082:8080
        - 5002:5001
    networks:
       private_net:
           ipv4_address: "192.168.1.102"

  open_config_node3:
    depends_on:
        - bootnode
    container_name: open_config_node3
    image: dadepo/ipfs-private:latest
    volumes:
        - /tmp/ipfs/nexus:/usr/local/nexus/
    expose:
        - 8080
        - 5001
    ports:
        - 8083:8080
        - 5003:5001
    command: 
        - /bin/sh 
        - -c 
        - |
          ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin "[\"*\"]"
          ipfs config --json API.HTTPHeaders.Access-Control-Allow-Credentials "[\"true\"]"
          ipfs daemon --migrate=true
    networks:
       private_net:
           ipv4_address: "192.168.1.103"

  mal_node4:
    depends_on:
        - bootnode
    container_name: mal_node4
    image: dadepo/ipfs-mal
    volumes:
        - /tmp/ipfs/nexus:/usr/local/nexus/
    expose:
        - 8080
        - 5001
    ports:
        - 8084:8080
        - 5004:5001
    networks:
       private_net:
           ipv4_address: "192.168.1.104"

  tcpdump:
   container_name: tcpdump
   image: corfr/tcpdump:latest
   volumes:
      - /tmp/ipfs/nexus/tcpdump:/data
   networks:
      private_net:
         ipv4_address: "192.168.1.200"

networks:
  private_net:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.1.0/24
